db:
  host: "localhost"
  port: 5432
  user: "testuser"
  password: "1234"
  dbname: "test"
  sslmode: "disable"

nats-streaming:
  host: "localhost"
  port: 4222
  cluster_id: "test-cluster"
  client_id: "subscriber-publisher"
  channel: "channel"

  http:
    port: 5000